augroup myvimrc
    au!
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END

filetype off

filetype plugin indent on

" ctrl module to start in the current dir
let g:ctrlp_working_path_mode = 'r'

vnoremap > >gv
vnoremap < <gv

if empty(glob('~/.vim/autoload/plug.vim'))
	  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
	      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
	    autocmd VimEnter * PlugInstall | source $MYVIMRC
    endif

call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'pearofducks/ansible-vim'
" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'
" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'
" Group dependencies, vim-snippets depends on ultisnips
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'ctrlpvim/ctrlp.vim'
" Plug 'spolu/dwm.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/base16-vim'
Plug 'dkprice/vim-easygrep'
Plug 'lepture/vim-jinja'
Plug 'fatih/vim-go'
Plug 'fatih/molokai'
Plug 'tpope/vim-sensible'
Plug 'jnurmine/Zenburn'
Plug 'scrooloose/syntastic'
Plug 'vim-scripts/indentpython.vim'
Plug 'nvie/vim-flake8'
Plug 'Valloric/YouCompleteMe'
Plug 'scrooloose/nerdtree'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'thecodesmith/vim-groovy'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'Yggdroot/indentLine'
" Plug 'edkolev/tmuxline.vim'
" Add plugins to &runtimepath
call plug#end()

let g:airline#extensions#tabline#enabled = 1
set laststatus=2

" set encoding=utf-8
set number
syntax enable
let g:solarized_termcolors = 16
set background=dark
colorscheme zenburn
let base16colorspace=256
let g:airline_theme = 'base16'
let python_highlight_all=1
" set term=screen-256color
set expandtab
syntax on

map <C-t> :NERDTreeToggle<CR>

au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

au BufNewFile,BufRead *.js, *.html, *.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2

au BufNewFile,BufRead *.groovy  setf groovy 
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2

au BufRead,BufNewFile ~/Work/Repos/*.yml
    \ set ft=ansible

highlight BadWhitespace ctermbg=red guibg=red
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/

" Syntastic plugin start
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_python_checkers = ['pyflakes']
" Syntastic plugin end
