augroup myvimrc
    au!
    au BufWritePost .vimrc,_vimrc,vimrc,.gvimrc,_gvimrc,gvimrc so $MYVIMRC | if has('gui_running') | so $MYGVIMRC | endif
augroup END

filetype off

filetype plugin indent on

" ctrl module to start in the current dir
let g:ctrlp_working_path_mode = 'c'

vnoremap > >gv
vnoremap < <gv

call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

" Ansible vim https://github.com/chase/vim-ansible-yaml.git
Plug 'chase/vim-ansible-yaml'
" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'junegunn/vim-easy-align'
" Any valid git URL is allowed
Plug 'https://github.com/junegunn/vim-github-dashboard.git'
" Group dependencies, vim-snippets depends on ultisnips
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'spolu/dwm.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'chriskempson/base16-vim'
Plug 'dkprice/vim-easygrep'
" Plug 'edkolev/tmuxline.vim'
" Add plugins to &runtimepath
call plug#end()

let g:airline#extensions#tabline#enabled = 1
set laststatus=2

set number
syntax enable
set background=dark
let g:solarized_termcolors = 256
colorscheme solarized
let g:airline_theme = 'base16'
